name: Schema Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install ajv ajv-formats ajv-errors ajv-keywords ajv-pack ajv-bsontype ajv-i18n ajv-oai202003 ajv-papaparse ajv-parsimmon ajv-errors prettier

      - name: Validate Schema
        run: node validate-recipe.js
