name: Schema Validation

on:
  push:
    branches:
      - main

jobs:
  schema-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Validate and Read Recipe
        uses: kiran-godse/GitOpsRainfall@main
        with:
          recipe-file: './recipes/cmake.json'

     
