name: Schema Validation

on:
  push:
    branches:
      - main

jobs:
  schema-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: Install npm dependencies
        run: npm install

      - name: Validate and Read Recipe
        run: node index.js  # Update this line to run the 'index.js' from the root directory
