name: Validate Recipe

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          always-auth: false
          check-latest: false

      - name: Install dependencies
        run: npm install ajv ajv-formats ajv-errors ajv-keywords ajv-pack ajv-bsontype ajv-i18n prettier

  

      - name: Validate recipe
        run: node src/validateRecipe.js
